const view = {
  currentPage: "home",
};

const game = {
  classChosen: false,

  chosenCharacter: null,
  currentLocation: "Starting Village",
  currentEnemy: null,
  day: 0,

  stats: {
    level: 0,
    gold: 100,
    maxHealth: 500,
    health: 500,
    maxEnergy: 100,
    energy: 100,
    xp: 0,
  },

  characters: [
    {
      name: "Knight",
      baseAttack: 30,
      id: 0,
    },
  ],

  locations: [
    {
      name: "Starting Village",
      id: 0,
      requiredLevel: 0,
      shopAvailable: true,
      canFight: false,
      travelCost: 50,
    },
    {
      name: "Forest",
      id: 1,
      requiredLevel: 0,
      shopAvailable: false,
      canFight: true,
      travelCost: 55,
      enemies: [
        {
          name: "Spider",
          maxhp: 100,
          hp: 100,
          attack: 15,
          level: 1,
          exp: 35,
          gold: 20,
          id: 0,
        },
        {
          name: "Giant Rat",
          maxhp: 170,
          hp: 170,
          attack: 20,
          level: 3,
          exp: 45,
          gold: 60,
          id: 1,
        },
        {
          name: "Wolf",
          maxhp: 300,
          hp: 300,
          attack: 30,
          level: 7,
          exp: 50,
          gold: 100,
          id: 2,
        },
      ],
    },
    {
      name: "Mountains",
      id: 2,
      requiredLevel: 10,
      shopAvailable: false,
      travelCost: 20,
      canFight: true,
      enemies: [
        {
          name: "Mountain Goat",
          maxhp: 400,
          hp: 400,
          attack: 35,
          level: 10,
          exp: 55,
          gold: 60,
          id: 0,
        },
        {
          name: "Stone Statue",
          maxhp: 800,
          hp: 800,
          attack: 36,
          level: 14,
          exp: 65,
          gold: 100,
          id: 1,
        },
        {
          name: "Gargoyle",
          maxhp: 300,
          hp: 300,
          attack: 70,
          level: 17,
          exp: 75,
          gold: 130,
          id: 2,
        },
      ],
    },
    {
      name: "Ice Ravine",
      id: 3,
      requiredLevel: 20,
      shopAvailable: false,
      travelCost: 50,
      canFight: true,
      enemies: [
        {
          name: "Ice Wolf",
          maxhp: 900,
          hp: 900,
          attack: 65,
          level: 21,
          exp: 105,
          gold: 60,
          id: 0,
        },
        {
          name: "Icicle Bat",
          maxhp: 300,
          hp: 300,
          attack: 106,
          level: 24,
          exp: 130,
          gold: 100,
          id: 1,
        },
        {
          name: "Ice Golem",
          maxhp: 1700,
          hp: 1700,
          attack: 40,
          level: 29,
          exp: 150,
          gold: 130,
          id: 2,
        },
      ],
    },

    {
      name: "Abanonded Village",
      id: 4,
      requiredLevel: 30,
      shopAvailable: true,
      travelCost: 30,
      canFight: true,
      enemies: [
        {
          name: "Zombie",
          maxhp: 1200,
          hp: 1200,
          attack: 65,
          level: 30,
          exp: 105,
          gold: 60,
          id: 0,
        },
        {
          name: "Infested Rat",
          maxhp: 700,
          hp: 700,
          attack: 70,
          level: 35,
          exp: 130,
          gold: 100,
          id: 1,
        },
        {
          name: "Weird Looking Thing",
          maxhp: 9999,
          hp: 9999,
          attack: 1,
          level: 99,
          exp: 1000,
          gold: 130,
          id: 2,
        },
      ],
    },
  ],

  experienceList: [],
};
